#!/bin/sh
# update the keystone repo
git -C /opt/keystone pull
if [ $? -ne 0 ]
then
    echo "Error updating keystone git repo"
    exit 1
fi
# update the database, fingers crossed...
keystone-manage --config-file /etc/keystone/keystone.conf db_sync
if [ $? -ne 0 ]
then
    echo "Error running keystone-manage"
    exit 1
fi
# start the keystone server
keystone-all --config-file /etc/keystone/keystone.conf
